# Generated by Django 3.0.6 on 2020-05-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_travel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
