# Generated by Django 3.0.6 on 2020-05-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='travel',
        ),
    ]
