# Generated by Django 3.0.6 on 2020-05-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0016_auto_20200520_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helo',
            name='id',
        ),
        migrations.AlterField(
            model_name='helo',
            name='on_text',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
