# Generated by Django 3.0.6 on 2020-05-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0020_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='helo',
            fields=[
                ('country', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ot', models.CharField(max_length=200)),
            ],
        ),
    ]
