# Generated by Django 3.0.6 on 2020-05-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0021_helo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='helo',
        ),
    ]
