# Generated by Django 3.0.6 on 2020-05-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0024_travel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='travel',
            new_name='Travel1',
        ),
    ]
