# Generated by Django 3.0.6 on 2020-05-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0025_auto_20200520_0311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travel1',
        ),
    ]
