# Generated by Django 3.0.6 on 2020-05-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('first', '0026_delete_travel1'),
    ]

    operations = [
        migrations.CreateModel(
            name='travelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
