# Generated by Django 3.0.6 on 2020-05-19 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0027_travelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='travelo',
        ),
    ]
